using System;
using UnityEngine;

namespace PsycheVR.Data
{
    /// <summary>Build identity generated by Tools > Build APK as a Resources JSON asset.</summary>
    [Serializable]
    public sealed class SessionBuildInfo
    {
        public const string ResourceName = "SessionBuildInfo";
        public string gitShortHash;
        public string buildTimeUtc;
        public string flavor;
        public int versionCode;

        public string Stamp => $"{gitShortHash} {buildTimeUtc} {flavor} v{versionCode}";

        /// <summary>Unbuilt editor runs never claim to be the last APK built here.</summary>
        public static string CurrentStamp
        {
            get
            {
                if (Application.isEditor) return "editor-unbuilt";
                var asset = Resources.Load<TextAsset>(ResourceName);
                if (asset == null) return "unstamped-" + Application.version;
                try { return JsonUtility.FromJson<SessionBuildInfo>(asset.text).Stamp; }
                catch (ArgumentException) { return "unstamped-" + Application.version; }
            }
        }
    }
}
